import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */

public class App {

    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

        WebDriver driver = new ChromeDriver();

        // Open SauceDemo website
        driver.get("https://www.saucedemo.com/");
        driver.manage().window().maximize();

        // Enter username
        driver.findElement(By.id("user-name")).sendKeys("standard_user");

        // Enter password
        driver.findElement(By.id("password")).sendKeys("secret_sauce");

        // Click login button
        driver.findElement(By.id("login-button")).click();

        // Print greeting
        System.out.println(new App().getGreeting());

        // Close browser
        driver.quit();
    }
}
